version: '3.8'

services:
  # Lang2Query Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lang2query-backend
    ports:
      - "8000:8000"
    environment:
      - PROVIDER=chatgpt
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o
      - KB_DIRECTORY=/app/src/kb
      - COLLECTION_NAME=sql_generation_kb
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./src/kb:/app/src/kb
      - ./src/retreiver/input:/app/src/retreiver/input
      - ./src/retreiver/output:/app/src/retreiver/output
    networks:
      - lang2query-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Lang2Query Frontend
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: lang2query-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    networks:
      - lang2query-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis (for caching and session storage)
  redis:
    image: redis:7-alpine
    container_name: lang2query-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lang2query-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ChromaDB (for vector storage)
  chromadb:
    image: chromadb/chroma:latest
    container_name: lang2query-chromadb
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - lang2query-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  chroma_data:
    driver: local

networks:
  lang2query-network:
    driver: bridge
