[project]
name = "lang2query"
version = "0.1.0"
requires-python = ">=3.10"

[tool.uv]
# You can continue to use requirements.txt for dependencies.
# If you later want to manage deps here, move them to [project] dependencies.

[tool.uv.scripts]
# Run the main app
dev = "python -m app.main"

# Build knowledge base
kb = "python -m app.kb.build_kb"

# Create/load database tables
db = "python -m db.create_tables"

# Convenient REPL inside the venv
repl = "ipython"

# Code quality
format = "ruff format && ruff check --fix"
lint = "ruff check"

[tool.ruff]
line-length = 100
target-version = "py312"
fix = true

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "UP", # pyupgrade
  "B",  # flake8-bugbear
  "C4", # flake8-comprehensions
]
ignore = [
]

[tool.black]
line-length = 100
target-version = ["py312"]
preview = true

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
tag_format = "v$version"

[tool.commitizen.change_type_map]
feat = "Features"
fix = "Bug Fixes"
perf = "Performance"
refactor = "Refactoring"
docs = "Documentation"
style = "Styling"
test = "Tests"
build = "Build"
ci = "CI"
chore = "Chores"
revert = "Reverts"
